### ISSUE TITLE
Log is too verbose when failed to send message

### ISSUE THREAD

**Issue by targos** [ES-Community/bot#24]
```
2021-03-22T15:18:17.814175+00:00 app[worker.1]: {"level":50,"time":1616426297813,"pid":4,"hostname":"949c9138-655c-4be7-91ad-5befa359baf7","id":"a3cdd05a-6ace-4196-916e-086f6122310a","type":"FormatChecker","name":"Link","name":"DiscordAPIError","message":"Cannot send messages to this user","method":"post","path":"/channels/823576326388056064/messages","code":50007,"httpStatus":403,"stack":"DiscordAPIError: Cannot send messages to this user\n    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)\n    at async FormatChecker._messageHandler (/app/build/src/framework/FormatChecker.js:54:13)","type":"Error","msg":"failed to send private message to user Romain Lanz 🦊#0042"}
```

**Comment by Mesteery** [comment]
https://github.com/ES-Community/bot/blob/8ad52d409dfb52d255491950355e1fc241925d80/src/framework/FormatChecker.ts#L83-L87
I suggest:
```diff
 logger.error( 
-  err, 
-  'failed to send private message to user %s', 
+  new Error('failed to send private message to user ' + author.tag),
-  author.tag, 
 );
```

**Comment by targos** [comment]
We should maybe check the error returned by Discord and:
- If it's a "normal error" (user doesn't allow DM from the bot), do not log
- Otherwise, keep the log as it is now

**Comment by targos** [comment]
Fixed in https://github.com/ES-Community/bot/pull/31
