### ISSUE TITLE
Error in EpicGames cron job

### ISSUE THREAD

**Issue by targos** [ES-Community/bot#36]
```
TypeError: Cannot read property 'startDate' of undefined
    at /app/build/src/crons/EpicGames.js:87:77
    at Array.filter (<anonymous>)
    at getOfferedGames (/app/build/src/crons/EpicGames.js:86:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Cron.handle [as handler] (/app/build/src/crons/EpicGames.js:23:23)
    at async Cron.executeJob (/app/build/src/framework/Cron.js:28:13)
```

**Comment by Mesteery** [comment]
```js
{
  data: {
    Catalog: {
      searchStore: {
        elements: [
          {
            title: 'A Plague Tale: Innocence',
            productSlug: 'a-plague-tale-innocence',
            keyImages: [
              {
                type: 'CodeRedemption_340x440',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/6890480d-5ce5-4e10-b0d5-4690552beac1_1200x1600-64d325ee5395304b0e91595b5e22e07c'
              },
              {
                type: 'Thumbnail',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/6890480d-5ce5-4e10-b0d5-4690552beac1_1200x1600-64d325ee5395304b0e91595b5e22e07c'
              },
              {
                type: 'OfferImageTall',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/6890480d-5ce5-4e10-b0d5-4690552beac1_1200x1600-64d325ee5395304b0e91595b5e22e07c'
              },
              {
                type: 'OfferImageWide',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/1bbe911a-6c89-490c-9230-cdd99c3be4b5_2560x1440-1c47786e1130e040a090368a1551a627'
              },
              {
                type: 'DieselStoreFrontTall',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/6890480d-5ce5-4e10-b0d5-4690552beac1_1200x1600-64d325ee5395304b0e91595b5e22e07c'
              },
              {
                type: 'DieselStoreFrontWide',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/1bbe911a-6c89-490c-9230-cdd99c3be4b5_2560x1440-1c47786e1130e040a090368a1551a627'
              }
            ],
            price: {
              totalPrice: { fmtPrice: { originalPrice: '39,99 €' } },
              lineOffers: [
                {
                  appliedRules: [
                    {
                      startDate: '2021-08-05T15:00:00.000Z',
                      endDate: '2021-08-12T15:00:00.000Z'
                    }
                  ]
                }
              ]
            }
          },
          {
            title: 'Minit',
            productSlug: 'minit/home',
            keyImages: [
              {
                type: 'CodeRedemption_340x440',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/MINIT_S2_1200x1600_1200x1600-b0002c8b3513c905c312d55069ca1213'
              },
              {
                type: 'DieselStoreFrontTall',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/MINIT_S2_1200x1600_1200x1600-b0002c8b3513c905c312d55069ca1213'
              },
              {
                type: 'DieselStoreFrontWide',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/MINIT_S1_2560x1440_2560x1440-ac642c99abfa88c9263ca1e996ed4373'
              },
              {
                type: 'OfferImageTall',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/MINIT_S2_1200x1600_1200x1600-b0002c8b3513c905c312d55069ca1213'
              },
              {
                type: 'OfferImageWide',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/MINIT_S1_2560x1440_2560x1440-ac642c99abfa88c9263ca1e996ed4373'
              },
              {
                type: 'Thumbnail',
                url: 'https://cdn1.epicgames.com/salesEvent/salesEvent/MINIT_S2_1200x1600_1200x1600-b0002c8b3513c905c312d55069ca1213'
              }
            ],
            price: {
              totalPrice: { fmtPrice: { originalPrice: '9,99 €' } },
              lineOffers: [
                {
                  appliedRules: [
                    {
                      startDate: '2021-08-05T15:00:00.000Z',
                      endDate: '2021-08-12T15:00:00.000Z'
                    }
                  ]
                }
              ]
            }
          }
        ],
        paging: { total: 2 }
      }
    }
  },
  extensions: {}
}
```
Pourtant `data.Catalog.searchStore.elements[0|1].price.lineOffers[0].appliedRules[0].startDate` et  et bien défini

**Comment by targos** [comment]
il ne l'était peut-être pas au moment où le bot a fait la requête

**Comment by Mesteery** [comment]
Certainement, mais dans ce cas c'est assez bizarre, il faudrait attendre 17h00 pour voir si cela se reproduit

**Comment by targos** [comment]
vu qu'on fait la requête seulement une fois par jour, je ne suis pas contre le fait d'ajouter un log du résultat

**Comment by targos** [comment]
https://github.com/ES-Community/bot/pull/37
