### ISSUE TITLE
EpicGames cron: parfois un jeu n'a pas de "lineOffers" ?

### ISSUE THREAD

**Issue by targos** [ES-Community/bot#66]
https://github.com/ES-Community/bot/actions/runs/3287402854/jobs/5416537744

```
FAIL tests/cron/EpicGames.spec.ts
  ● getOfferedGames

    TypeError: Cannot read properties of null (reading 'lineOffers')

      226 |   // Keep only the games that were offered in the last day.
      227 |   const games = (catalog.elements ?? []).filter((game) => {
    > 228 |     const rule = game.price.lineOffers[0].appliedRules[0];
          |                             ^
      229 |     const [startDate, endDate] = [
      230 |       new Date(rule.startDate),
      231 |       new Date(rule.endDate),

      at src/crons/EpicGames.ts:228:29
          at Array.filter (<anonymous>)
      at getOfferedGames (src/crons/EpicGames.ts:227:42)
      at Object.<anonymous> (tests/cron/EpicGames.spec.ts:[12](https://github.com/ES-Community/bot/actions/runs/3286092414/jobs/5416496826#step:6:13):[19](https://github.com/ES-Community/bot/actions/runs/3286092414/jobs/5416496826#step:6:20))
```

**Comment by Purexo** [comment]
c'est plutôt parfois un jeu n'a pas de price j'ai l'impression.
Je vais jeter un oeil.
